### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by stevenhuakui** [ashispati/ar-vae#1]
Dear Ashis Pati,

I found your research interesting and wanted to try your code. However, I ran into an error when running the installation code 'pip install -e .'. It seems that you should provide a setup.py file. I really appreciate it if you could fix it. Thanks!

Best,
Kui.

**Comment by ashispati** [comment]
Can you post what error you are getting?

There seems to some issue with editable pip installs using `pip install -e .` (even if I add a `setup.py` file). I am trying to find a workaround for this. 

However, if you should able to use the code without needing to install it if you have created a conda environement as mentioned. in the `readme`.

**Comment by ashispati** [comment]
Using `python setup.py develop` should work. Have updated the readme also.

**Comment by stevenhuakui** [comment]
Thanks! The setup worked now.  However, except the test_mnist.py, running other scripts gave errors. Here are the errors I got:
1. For the train_image_*.py, they require file 'data/mnist_data/plain/train-images-idx3-ubyte.gz' that does not exist.
2. For the train_measure_vae.py, it requires file 'data/folk_raw_data' that does not exist.
3. For the script_create_result_plots.py, it reported that " No such file or directory: 'download_dsprites.sh': 'download_dsprites.sh' "

I ran these script directly using "python *.py", I am not sure if I should run some other scripts before using these ones. Hope you could give some advice or fix the errors if they are real errors.

**Comment by ashispati** [comment]
Ah, yes. I need to update the steps to download the different datasets in the README.

**Comment by ashispati** [comment]
I have added the instructions on how to download the different datasets.
