### ISSUE TITLE
Missing model MnistRESNET.pt

### ISSUE THREAD

**Issue by vicentepedro** [ashispati/ar-vae#2]
Dear Ashis Pati,

Thanks for your article and for sharing your code.

when running the script: 
`python train_image_vae.py
`
I got the following error:
`No such file or directory: ar-vae/models/MnistRESNET/MnistRESNET.pt`

It is related with the call:
```
ar-vae/imagevae/image_vae_trainer.py", line 261, in eval_model
    metrics = self.compute_eval_metrics()
```

Where can I found this model?

**Comment by ashispati** [comment]
Hi, thanks for reaching out. I have added the model file to th GitHub repo in the releases section. You can download it from here: https://github.com/ashispati/ar-vae/releases/download/0.1/MnistRESNET.pt
Also, updated the readme file. Let me know if this works for you.
