### ISSUE TITLE
Missing model MnistRESNET.pt

### ISSUE THREAD

**Issue by xiaohan2** [ashispati/ar-vae#3]
Dear Ashis Pati, I am very interested in your research. But it cannot run because of lack of MnistRESNET.pt. Can I get the file~ Thank you.My email is cyh19work@163.com.

**Comment by ashispati** [comment]
Hi, thanks for reaching out. I have added the model file to th GitHub repo in the releases section. You can download it from here: https://github.com/ashispati/ar-vae/releases/download/0.1/MnistRESNET.pt
Also, updated the readme file. Let me know if this works for you.
